name: createimage

on:
  - push

env:
  STORAGE_ACCOUNT: 'lhtestingrunnerimage'

jobs:
  hcp-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: install `packer` plugins
        run: "packer plugins install github.com/hashicorp/azure"

      - name: Run `packer init`
        id: init
        run: "packer init ./images/ubuntu/templates/ubuntu-24.04.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./images/ubuntu/templates/ubuntu-24.04.pkr.hcl"
        env:
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          managed_image_name: "ubuntu-24.04-${{ github.run_id }}-${{ github.run_attempt }}"
          managed_image_resource_group: ${{ secrets.MANAGED_IMAGE_RESOURCE_GROUP }}
          resource_group_name: ${{ secrets.MANAGED_IMAGE_RESOURCE_GROUP }}
          storage_account: ${{ env.STORAGE_ACCOUNT }}
          tenant_id: ${{ secrets.TENANT_ID }}


      - name: Build Artifact
        run: packer build -color=false -on-error=abort ./images/ubuntu/templates/ubuntu-24.04.pkr.hcl
        env:
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          managed_image_name: "ubuntu-24.04-${{ github.run_id }}-${{ github.run_attempt }}"
          managed_image_resource_group: ${{ secrets.MANAGED_IMAGE_RESOURCE_GROUP }}
          resource_group_name: ${{ secrets.MANAGED_IMAGE_RESOURCE_GROUP }}
          storage_account: ${{ env.STORAGE_ACCOUNT }}
          tenant_id: ${{ secrets.TENANT_ID }}
